/**
 * @fileoverview gRPC-Web generated client stub for sales.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: sales.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as sales_pb from './sales_pb'; // proto import: "sales.proto"


export class SalesServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUploadCSV = new grpcWeb.MethodDescriptor(
    '/sales.v1.SalesService/UploadCSV',
    grpcWeb.MethodType.UNARY,
    sales_pb.UploadRequest,
    sales_pb.UploadResponse,
    (request: sales_pb.UploadRequest) => {
      return request.serializeBinary();
    },
    sales_pb.UploadResponse.deserializeBinary
  );

  uploadCSV(
    request: sales_pb.UploadRequest,
    metadata?: grpcWeb.Metadata | null): Promise<sales_pb.UploadResponse>;

  uploadCSV(
    request: sales_pb.UploadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: sales_pb.UploadResponse) => void): grpcWeb.ClientReadableStream<sales_pb.UploadResponse>;

  uploadCSV(
    request: sales_pb.UploadRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: sales_pb.UploadResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sales.v1.SalesService/UploadCSV',
        request,
        metadata || {},
        this.methodDescriptorUploadCSV,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sales.v1.SalesService/UploadCSV',
    request,
    metadata || {},
    this.methodDescriptorUploadCSV);
  }

  methodDescriptorDownloadResult = new grpcWeb.MethodDescriptor(
    '/sales.v1.SalesService/DownloadResult',
    grpcWeb.MethodType.UNARY,
    sales_pb.DownloadRequest,
    sales_pb.DownloadResponse,
    (request: sales_pb.DownloadRequest) => {
      return request.serializeBinary();
    },
    sales_pb.DownloadResponse.deserializeBinary
  );

  downloadResult(
    request: sales_pb.DownloadRequest,
    metadata?: grpcWeb.Metadata | null): Promise<sales_pb.DownloadResponse>;

  downloadResult(
    request: sales_pb.DownloadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: sales_pb.DownloadResponse) => void): grpcWeb.ClientReadableStream<sales_pb.DownloadResponse>;

  downloadResult(
    request: sales_pb.DownloadRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: sales_pb.DownloadResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sales.v1.SalesService/DownloadResult',
        request,
        metadata || {},
        this.methodDescriptorDownloadResult,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sales.v1.SalesService/DownloadResult',
    request,
    metadata || {},
    this.methodDescriptorDownloadResult);
  }

}

